### PR TITLE
Add Aeza

### PR DESCRIPTION
**Pull request by cofob**
We use NixOS to manage our internal infrastructure.

### CODE REVIEW

**Comment by ad-si** [comment]
Thank! Can you please also add an entry to `references.md`?

**Comment by cofob** [comment]
> Thank! Can you please also add an entry to `references.md`?

Added :)

**Comment by ad-si** [comment]
Ideally the entry would also include a link. 😅
Is there no public link / reference that makes it obvious that Aeza is using Nix?

**Comment by ad-si** [comment]
Merged for now, but let me know if you have a link as the reference @cofob!

**Pull request merged**
